### ISSUE TITLE
Feature Idea: Hardware wallet support

### ISSUE THREAD

**Issue by decanus** [status-im/nim-status-client#559] opened 2020-07-14 09:58 UTC
Considering status desktop client has a browser etc in it, it would be nice to be able to connect ones hardware wallet. This could probably be facilitated through the go-ethereum bindings for hardware wallets.

**Comment by iurimatias** [comment] 2020-10-21 13:58
duplicate of #1156 (or rather the other way around, but the other has other comments)

**Closed by iurimatias** 2020-10-21 13:58 UTC
Labels: enhancement
