### ISSUE TITLE
Feat: style emoji picker according to design

### ISSUE THREAD

**Issue by emizzle** [status-im/nim-status-client#1073] opened 2020-09-30 23:13 UTC
@jrainville styled the picker in figma: https://www.figma.com/file/Mr3rqxxgKJ2zMQ06UAKiWL/%F0%9F%92%AC-Chat%E2%8E%9CDesktop?node-id=2617%3A256

<img width="1015" alt="Screenshot 2020-09-29 at 16 29 13" src="https://user-images.githubusercontent.com/52249767/94572159-fd0ccf80-0270-11eb-8120-ba557ba9d010.png">

_Originally posted by @simonricoo in https://github.com/status-im/nim-status-client/pull/1002#issuecomment-700744219_

**Comment by jrainville** [comment] 2020-10-01 13:28
This is a duplicate of https://github.com/status-im/nim-status-client/issues/1046 , but yours is better described so I'll close the other

**Closed** 2020-10-20 21:21 UTC
